models/Ticket.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "ticket".
 *
 * @property int $id
 * @property string|null $mobile
 * @property string|null $date_created
 * @property string|null $status
 * @property string|null $ticket_status
 * @property int|null $user_id
 *
 * @property Incoming[] $incomings
 * @property Orders[] $orders
 * @property Outgoing[] $outgoings
 * @property Users $user
 */
class Ticket extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'ticket';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['date_created'], 'safe'],
            [['ticket_status'], 'string'],
            [['user_id'], 'integer'],
            [['mobile'], 'string', 'max' => 15],
            [['status'], 'string', 'max' => 1],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mobile' => 'Mobile',
            'date_created' => 'Date Created',
            'status' => 'Status',
            'ticket_status' => 'Ticket Status',
            'user_id' => 'User ID',
        ];
    }

    /**
     * Gets query for [[Incomings]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIncomings()
    {
        return $this->hasMany(Incoming::className(), ['ticket_id' => 'id']);
    }

    /**
     * Gets query for [[Orders]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getOrders()
    {
        return $this->hasMany(Orders::className(), ['ticketId' => 'id']);
    }

    /**
     * Gets query for [[Outgoings]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getOutgoings()
    {
        return $this->hasMany(Outgoing::className(), ['ticket_id' => 'id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(Users::className(), ['id' => 'user_id']);
    }

        public static function get_user_message($mobile){
        $model = Incoming::find()->where(["mobile" => $mobile])->one();
        if(!empty($model)){
            return $model->msg;
        }

        return null;
    }

    public static function get_cashier_reply($mobile){
        $model = Outgoing::find()->where(["dest" => $mobile])->one();
        if(!empty($model)){
            return $model->msg;
        }

        return null;
    }


    public function incoming(){
        $query = Yii::$app->db->createCommand("SELECT i.`msg` FROM `ticket` AS t INNER JOIN `incoming` AS i ON t.`id`=i.`ticket_id` WHERE t.`mobile`=254745725567 AND t.`ticket_status`='Pending'")
            ->execute();
    }

    public function outgoing(){

        if (isset($_POST) && !empty($_POST)) {

            $data = $_POST;
            $chat_message =  $data['chat_message'];
            $mobile = 14155238886;
            $destination = 254701405514;
            $ticketid = 4;
            $msg_id = 5;
            $state = "ticket";

            var_dump($data);die();

            
            Yii::$app->db->createCommand("INSERT INTO outgoing (mobile,msg,dest,ticket_id,state,msg_id) VALUES ('".$mobile."','".$chat_message."','".$destination."','".$ticketid."','".$state."','".$msg_id."') ")
            ->execute();

            return true;

        }
        return false;

        // var_dump($query);
        // die();
    }
}

controllers/TicketController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Ticket;
use app\models\TicketSearch;
use app\models\Outgoing;
use app\models\TicketActiveSearch;
use app\models\TicketClosedSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TicketController implements the CRUD actions for Ticket model.
 */
class TicketController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Ticket models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TicketSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionIndexactive()
    {
        $searchModel = new TicketActiveSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('indexactive', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionIndexclosed()
    {
        $searchModel = new TicketClosedSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('indexclosed', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Ticket model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionViewdemo($id)
    {
        return $this->render('viewdemo', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionViewactivedemo($id)
    {
        return $this->render('viewactivedemo', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Ticket model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Ticket();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Ticket model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionUpdatedemo($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {

            

            if($model->save()){

            $mobile = 14155238886;
            $destination = $model->mobile;
            $ticketid = $model->id;
            $state = "ticket";
            $status = "Pending";

            $msg = (new \yii\db\Query())
                ->select(['incoming.id'])
                ->from('ticket')
                ->join('LEFT JOIN', 'incoming', 'ticket.id = incoming.ticket_id')
                ->where(['ticket.mobile' => $model->mobile])
                ->andwhere(['incoming.ticket_id'=> $model->id])
                ->andwhere(['ticket.ticket_status'=>'Pending'])
                ->one();

            $msg_id = $msg['id'];
            
            Yii::$app->db->createCommand("INSERT INTO outgoing (mobile,msg,dest,ticket_id,state,msg_id) VALUES ('".$mobile."','".$model->reply."','".$model->mobile."','".$model->id."','".$state."','".$msg_id."') ")
            ->execute();

            Yii::$app->db->createCommand("UPDATE ticket SET `ticket_status` = 'Active' WHERE `id` = ".$model->id." AND `mobile`= ".$model->mobile." AND `ticket_status`='Pending'")
            ->execute();

            return $this->redirect(['viewdemo', 'id' => $model->id]);

            }else{

                Yii::$app->session->setFlash('error', 'Reply not successful. Kindly try resending again.');

                return $this->redirect(['updatedemo']);

            }
        }

        return $this->render('updatedemo', [
            'model' => $model,
        ]);
    }

    public function actionUpdateactivedemo($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {

            

            if($model->save()){

            $mobile = 14155238886;
            $destination = $model->mobile;
            $ticketid = $model->id;
            $state = "ticket";
            $status = "Active";

            $msg = (new \yii\db\Query())
                ->select(['incoming.id'])
                ->from('ticket')
                ->join('LEFT JOIN', 'incoming', 'ticket.id = incoming.ticket_id')
                ->where(['ticket.mobile' => $model->mobile])
                ->andwhere(['incoming.ticket_id'=> $model->id])
                ->andwhere(['ticket.ticket_status'=>'Active'])
                ->one();

            $msg_id = $msg['id'];
            
            Yii::$app->db->createCommand("INSERT INTO outgoing (mobile,msg,dest,ticket_id,state,msg_id) VALUES ('".$mobile."','".$model->reply."','".$model->mobile."','".$model->id."','".$state."','".$msg_id."') ")
            ->execute();

            return $this->redirect(['viewactivedemo', 'id' => $model->id]);

            }else{

                Yii::$app->session->setFlash('error', 'Reply not successful. Kindly try resending again.');

                return $this->redirect(['updateactivedemo']);

            }
        }

        return $this->render('updateactivedemo', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Ticket model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Ticket model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Ticket the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Ticket::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionFetchIncomingMessage(){

        $model = new Ticket();

        $data = $model->incoming();
    }

    public function actionAjax12(){
        echo "we here";

        $model = new Ticket();

        $data = $model->outgoing();
    }

    // public function actionAjax()
    // {
    //     $model = new Ticket();
    //     if ($model->load(Yii::$app->request->post())) {
    //           $data = Yii::$app->request->post();
    //           $msisdn = Yii::$app->user->username;
    //           $msisdn = "254" . substr($msisdn, -9);
    //           $searchModel = new TicketSearch();
    //           $dataProvider = $searchModel->searchajax($msisdn);
    //            return $this->render('index', [
    //           'searchModel' => $searchModel,
    //           'dataProvider' => $dataProvider,
    //       ]);

    //    } else {

    //         return $this->render('index1', [
    //             'model' => $model,
    //         ]);
    //     }

    //
    public function actionAjax()
    {

        $id  = isset($_POST['id']) ? $_POST['id'] : null;
        $msg = isset($_POST['msg']) ? $_POST['msg'] : null;
        $sql    = "select * from ticket where id=:id";
        $ticket = Yii::$app->db->createCommand($sql, [
             ':id' => (int) $id
        ])->queryOne();

        if(!$ticket)
        {
            return $this->asJson([
                'status' => false,
                'statusText' => '404 Content not found',
            ]);
        }

        if(!$msg)
        {
            return $this->asJson([
                'status' => false,
                'statusText' => 'The message cannot be empty',
            ]);
        }

        $model = new Outgoing();
        $model->mobile      = Yii::$app->user->identity->username;
        $model->dest        = '14155238886';
        $model->ticket_id   = $id;
        $model->state       = 'ticket';
        $model->msg         = \yii\helpers\Html::encode($msg);
        $model->created_at  = new \yii\db\Expression('NOW()');

        if($model->save() == false)
        {
            return $this->asJson([
                'status' => false,
                'statusText' => 'An error occurred while trying to save your data. please refresh your browser and try again',
                'errors'      => $model->getErrors(),
            ]);
        }

        $model->refresh();

        return $this->asJson([
            'status' => true,
            'item'   => [
                'id'         => $model->id,

controllers/TicketsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Tickets;
use app\models\TicketsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TicketsController implements the CRUD actions for Tickets model.
 */
class TicketsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Tickets models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TicketsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Tickets model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Tickets model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Tickets();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Tickets model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Tickets model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Tickets model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Tickets the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Tickets::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/ticket/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Ticket */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="ticket-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'mobile')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'date_created')->textInput() ?>

    <?= $form->field($model, 'status')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'ticket_status')->dropDownList([ 'Active' => 'Active', 'Pending' => 'Pending', 'Closed' => 'Closed', ], ['prompt' => '']) ?>

    <?= $form->field($model, 'user_id')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/ticket/_formactivedemo.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Ticket */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="ticket-form">
    <!--display success message-->
    <?php if (Yii::$app->session->hasFlash('success')): ?>
        <div class="alert alert-success alert-dismissable">
             <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
             <h4><i class="icon fa fa-check"></i>Saved!</h4>
             <?= Yii::$app->session->getFlash('success') ?>
        </div>
    <?php endif; ?>

    <!--display error message-->
    <?php if (Yii::$app->session->hasFlash('error')): ?>
        <div class="alert alert-danger alert-dismissable">
             <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
             <h4><i class="icon fa fa-remove"></i>Not Saved!</h4>
             <?= Yii::$app->session->getFlash('error') ?>
        </div>
    <?php endif; ?>

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'mobile')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'reply')->textarea(['rows' => 15]) ?>

    <div class="form-group">
        <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/ticket/_formdemo.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Ticket */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="ticket-form">
    <!--display success message-->
    <?php if (Yii::$app->session->hasFlash('success')): ?>
        <div class="alert alert-success alert-dismissable">
             <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
             <h4><i class="icon fa fa-check"></i>Saved!</h4>
             <?= Yii::$app->session->getFlash('success') ?>
        </div>
    <?php endif; ?>

    <!--display error message-->
    <?php if (Yii::$app->session->hasFlash('error')): ?>
        <div class="alert alert-danger alert-dismissable">
             <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
             <h4><i class="icon fa fa-remove"></i>Not Saved!</h4>
             <?= Yii::$app->session->getFlash('error') ?>
        </div>
    <?php endif; ?>

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'mobile')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'reply')->textarea(['rows' => 15]) ?>

    <div class="form-group">
        <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/ticket/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\TicketSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="ticket-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'mobile') ?>

    <?= $form->field($model, 'date_created') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'ticket_status') ?>

    <?php // echo $form->field($model, 'user_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/ticket/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Ticket */

$this->title = 'Create Ticket';
$this->params['breadcrumbs'][] = ['label' => 'Tickets', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ticket-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/ticket/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use app\assets\AppAsset;
use kartik\grid\GridView;
use kartik\export\ExportMenu;
use app\models\Ticket;


use app\assets\chat\ChatAsset;
ChatAsset::register($this);

Yii::setAlias('@js', '@web/js/');


/* @var $this yii\web\View */
/* @var $searchModel app\models\TicketSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
AppAsset::register($this);
Yii::setAlias('@js', '@web/js/');


$this->title = 'Pending Tickets';
$this->params['breadcrumbs'][] = $this->title;
?>
<head>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
<style type="text/css">
    .panel-primary > .panel-heading {
    color: #fff;
    background-color: #465A6E;
    border-color: #465A6E;
    }
    .btn-primary {
        color: #fff;
        background-color: #465A6E;
        border-color: #465A6E;
        border-radius: 35px;
    }
    .pagination > .active > a, .pagination > .active > span, .pagination > .active > a:hover, .pagination > .active > span:hover, .pagination > .active > a:focus, .pagination > .active > span:focus {
        z-index: 3;
        color: #fff;
        cursor: default;
        background-color: #465A6E;
        border-color: #465A6E;
    }
    .red {
        color: white;
        background: red;
    }
    .btnstatus {
        border-radius: 35px;
        margin-bottom: 5px;
        margin-right: 5px;
        padding: 6px 12px;
        font-size: 14px;
        line-height: 1.42857143;
        touch-action: manipulation;
        cursor: pointer;
        background-image: none;
        border: 1px solid transparent;
        display: inline-block;
        font-weight: normal;
        text-align: center;
        white-space: nowrap;
        vertical-align: middle;
    }
</style>
</head>
<div class="ticket-index">

    <h3 style="padding-bottom: 5px;margin-top: -10px"><?= Html::encode($this->title) ?></h3>
    <p>
    <?php echo ExportMenu::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            
            //'id',
            'mobile',
            'msg:ntext',
            'dest',
            'ticket_id',
            //'created_at',
            //'state',
            //'acc_id',
        ],
        
    ]); ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'kartik\grid\SerialColumn'],

            // /'id',
            'mobile',
            [
            'label' => 'Message',
            'value' => function($data){
                return Ticket::get_user_message($data->mobile);
            },
            ],
            //'ticket_status',
            'date_created',
            [
            'attribute'=>'ticket_status',
            'header'=>'Ticket Status',
            'format'=>'raw',    
            'value' => function($model, $key, $index)
            {   
                    return '<button class="btnstatus red">Pending</button>';
            },
            ],
            //'user_id',
            [
                'header' => '',
                'format'    => 'raw',
                'value'     => function($model){

                    $text    = 'Zoom Live Chat';
                    $options = [
                        'class'        => 'btn btn-primary btn-block',
                        'data-runtime' => 'addTiket',
                        'title'        => $text,
                        'data-pjax'    => '0',
                        'data-id'      => $model->id,
                    ];
                    return Html::a($text,'javascript:void(0)', $options);
                },
            ],            
            [
                     'class' => 'yii\grid\ActionColumn',
                     'template' => '{updatedemo}',
                     'buttons' => [
                     'updatedemo' => function ($data, $key,$url) {
                        return Html::a('Reply (DEMO)',['updatedemo','id' => $key['id']], 
                        [ 'title' => 'Reply (DEMO)','data-pjax' => '0','class' => 'btn btn-primary',]
                        );
                        }
                     
                        ],
            ],
            [
                'class' => 'kartik\grid\ActionColumn',
                'template' => '{view}',
                'dropdown' => true,
                'vAlign'=>'middle',
            ],

        ],
        'containerOptions' => ['style'=>'overflow: auto'], 
        'toolbar' =>  [
            //'{export}',
            '{toggleData}'
        ],
        'pjax' => true,
        'bordered' => true,
        'striped' => false,
        'condensed' => true,
        'responsive' => true,
        'hover' => true,
        'floatHeader' => false,
        //'showPageSummary' => true,
        'rowOptions' => ['class' => ''],
        'headerRowOptions' => ['class' => ''],
        'layout' => "{items}\n{pager}",
        'panel' => [
            'type' => GridView::TYPE_PRIMARY
        ],
    ]); ?>


</div>

<?php
   $this->registerJs('
    $("a[data-runtime=addTiket]").on("click", function(event){
        event.preventDefault();
        event.stopPropagation();
        $(this).chat({
          "title":"WhatsApp Live Chat",
          "iconClass":"fa fa-whatsapp",
          "routes":{
            "add"     : "'. Url::toRoute(['/ticket/ajax'])     .'" ,
            "history" : "'. Url::toRoute(['/ticket/history'])  .'" ,
          }
        });
        return false;
    });
  ', $this::POS_END, 'ticket-msn');

views/ticket/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Ticket */

$this->title = 'Update Ticket: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Tickets', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="ticket-update">

    <h3 style="padding-bottom: 5px;margin-top: -10px"><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/ticket/updateactivedemo.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Ticket */

$this->title = 'Reply To Ticket: ' . $model->mobile;
$this->params['breadcrumbs'][] = ['label' => 'Tickets', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="ticket-update">

    <h3 style="padding-bottom: 5px;margin-top: -10px"><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_formactivedemo', [
        'model' => $model,
    ]) ?>

</div>

views/ticket/updatedemo.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Ticket */

$this->title = 'Reply To Ticket: ' . $model->mobile;
$this->params['breadcrumbs'][] = ['label' => 'Tickets', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="ticket-update">

    <h3 style="padding-bottom: 5px;margin-top: -10px"><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_formdemo', [
        'model' => $model,
    ]) ?>

</div>

views/ticket/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Ticket */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Tickets', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="ticket-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'mobile',
            'date_created',
            'status',
            'ticket_status',
            'user_id',
        ],
    ]) ?>

</div>